swagger: "2.0"
info:
  description: "Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available." 
  version: ""
  title: "swapi"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "swapi.co"
basePath: "/api"
tags: 
- name: "people"
  description: "Create Documentation of swapi APIs"
  externalDocs:
    description: "Find out more"
    url: "http://swapi.co"
- name: "schema"
  description: "View JSON schema for the resource"
  externalDocs:
    description: "Type of person in the Star War Universe"
    url: "http://swapi.co"
schemes: 
    - "http"

paths:
  /people:
    
    get:
      tags:
      - "people"
      summary: "Fetches all people"
      description: "Returns all people resources of the Star War apis"
      operationId: "getPeople"
      produces:
      - "application/json"
      
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/FinalResult"
        400:
          description: "Invalid resource"
        404:
          description: "People not found"
          
  /people/{people_id}:
    get:
      tags:
      - "people"
      summary: "Find people by ID"
      description: "Returns people with people_id"
      operationId: "getPeopleById"
      produces:
      - "application/json"
      parameters:
      - name: "people_id"
        in: "path"
        description: "ID of people to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/People"
        400:
          description: "Invalid ID supplied"
        404:
          description: "People not found"
    
  /people/schema/ :
    get:
      tags:
      - "schema"
      summary: "Find people's schema"
      description: "Returns people resources whole schema"
      operationId: "getPeopleBySchema"
      produces:
      - "application/json"
     
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/FinalResult"
        400:
          description: "Invalid schema supplied"
        404:
          description: "People schema not found"
      
    
definitions:
  People:
    type: "object"
    properties:
      name:
        type: "string"
        
      height:
        type: "integer"
        format: "int64"
      mass:
        type: "integer"
        format: "int64"
      hair_color:
        type: "string"
      skin_color:
        type: "string"
      eye_color:
        type: "string"
      birth_year:
        type: "string"
      gender:
        type: "string"
      homeworld:
        type: "string"
      films:
        type: "array"
        items:
          type: "string"
      species:
        type: "array"
        items:
          type: "string"
      vehicles:
        type: "array"
        items:
          type: "string"
      starships:
        type: "array"
        items:
          type: "string"
      created:
        type: "string"
      edited:
        type: "string"
      url:
        type: "string"
  FinalResult:
    type: "object"
    properties:
      count:
        type: "integer"
        format: "int64"
      next:
        type: "string"
      previous:
        type: "null"
      results:
        type: "array"
        items:
          type: "object"
          properties:
            name:
              type: "string"
                
            height:
              type: "integer"
              format: "int64"
            mass:
              type: "integer"
              format: "int64"
            hair_color:
              type: "string"
            skin_color:
              type: "string"
            eye_color:
              type: "string"
            birth_year:
              type: "string"
            gender:
              type: "string"
            homeworld:
              type: "string"
            films:
              type: "array"
              items:
                type: "string"
            species:
              type: "array"
              items:
                type: "string"
            vehicles:
              type: "array"
              items:
                type: "string"
            starships:
              type: "array"
              items:
                type: "string"
            created:
              type: "string"
            edited:
              type: "string"
            url:
              type: "string"
      
  Schema:
    type: "object"
    properties:
      type: 
        type: "string"
      required:
        type: "array"
        items:
          type: "string"
      schema:
        type: "string"
      properties:
        type: "object"
        properties:
          species:
            type: "object"
            properties:
              type: 
                type: "string"
              description:
                type: "string"
          homeworld:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          mass:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          skin_color:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          films:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          starships:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          edited:
            type: "object"
            properties:
              type: 
                type: "string"
                format: "date-time"
              description: 
                type: "string"
          gender:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          hair_color:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          vehicles:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          eye_color:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          url:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          birth_year:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          created:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          height:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
          name:
            type: "object"
            properties:
              type: 
                type: "string"
              description: 
                type: "string"
      description:
        type: "string"
      title:
        type: "string"
          
    

externalDocs:
  description: "Find out more about Swapi"
  url: "http://swapi.co"
